apiVersion: apps/v1
kind: Deployment
metadata:
  name: MLOps_operations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MLOps_operations
  template:
    metadata:
      labels:
        app: MLOps_operations
    spec:
      containers:
      - name: MLOps_operations
        image: haziq/python:0.0.1
        ports:
        - containerPort: 8080
